### ISSUE TITLE
Type definition file seems to be out of sync

### ISSUE THREAD

**Issue by kraaden** [markcellus/cookie-store#132]
According to the type definition file in NPM, the set method only accepts two strings:

    /**
     * Set a cookie.
     *
     * @param {string} name
     * @param {string} value
     * @return {Promise}
     */
    set(name: string, value: string): Promise<void>;

However if you check the code in the repository, it also accepts an object with many properties. It looks like the type definition file is out of sync and was not updated properly before publishing to NPM.

**Comment by markcellus** [comment]
Thanks @kraaden! Yes, this is because there have been a lot of updates made to the codebase since the last time the package was published to npm. If you look at [the `set()` for 3.0 (latest version on npm)](https://github.com/markcellus/cookie-store/blob/v3.0.0/index.ts#L264), it should show you what the code was at the time it was published. 

I believe just publishing another version with the latest codebase should sync the Type definition file with the latest source code on master branch. But I'll leave it to @keithamus to determine when it's a good idea to do that.

**Comment by Chaostheorie** [comment]
@kraaden  when the next release (or sub-version update) planned on NPM? I personally have only recently learned about the new `CookieStore` API, and I'm really grateful for your polyfill (or speculative-polyfill? #135) implementation. But the NPM release lacks important functionality without the `set()` options, such as expires …. Since a complete `set()` function is already implemented, on the master branch, I wanted to request a new (pre-)release for NPM.

**Comment by keithamus** [comment]
@koddsson and I have been working on this in 20% time. I'm on leave right now but we'll get back to it soon, complete the implementation and cut a release on npm. In the mean time if you're interested in trying this out you could install a git ref using npm, but fair warning the code in the main branch is not complete.

**Comment by markcellus** [comment]
Just to update everyone here: We're planning to bring the latest published npm version in sync to minimize the confusion. However, the current code isn't quite ready to be pushed as latest npm package, so I placed it into a next branch and published it to NPM under `next` tag. 

```
npm i cookie-store@next
```

That can be used to get types in sync for now. We'll update everyone here once the project is ready to be published under `latest`.
